# Generated by Django 4.1 on 2022-09-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
