# Generated by Django 4.1 on 2022-09-22 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("brand_logo", models.ImageField(upload_to="photos/brands")),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=255)),
                (
                    "cat_image",
                    models.ImageField(default="", upload_to="photos/categories/"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200, unique=True)),
                ("product_code", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("details", models.TextField(blank=True, max_length=500)),
                ("price", models.IntegerField()),
                ("images", models.ImageField(upload_to="photos/products")),
                ("images1", models.ImageField(upload_to="photos/products")),
                ("images2", models.ImageField(upload_to="photos/products")),
                ("stock", models.IntegerField()),
                ("is_available", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("material", models.CharField(blank=True, max_length=100)),
                ("occasion", models.CharField(blank=True, max_length=100)),
                ("type", models.CharField(blank=True, max_length=100)),
                ("pattern", models.CharField(blank=True, max_length=100)),
                ("country_of_origin", models.CharField(blank=True, max_length=100)),
                ("Manufacture", models.TextField(blank=True, max_length=500)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.brand"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="brand",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.category"
            ),
        ),
    ]
