# Generated by Django 4.1 on 2022-09-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="category",
        ),
    ]
