# Generated by Django 4.1 on 2022-10-01 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_cart_variation_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.TextField(max_length=200, unique=True),
        ),
    ]
