# Generated by Django 4.1 on 2022-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_coupon_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="offer_price",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=3),
        ),
    ]
