# Generated by Django 4.1 on 2022-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_alter_product_offer_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="offer_price",
            field=models.IntegerField(default=0),
        ),
    ]
