# Generated by Django 4.1 on 2022-10-17 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_alter_brandoffer_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryoffer",
            name="discount",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(50),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="productoffer",
            name="discount",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(50),
                    django.core.validators.MinValueValidator(1),
                ]
            ),
        ),
    ]
