# Generated by Django 4.1 on 2022-10-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_alter_categoryoffer_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="return_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="return_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Shipped", "Shipped"),
                    ("Returned", "Returned"),
                    ("Waiting for return", "Waiting for return"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="New",
                max_length=20,
            ),
        ),
    ]
